name: codezip
channels:
  - defaults
dependencies:
  - brotlicffi=1.2.0.0=py310h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2026.01.04=py310haa95532_0
  - cffi=2.0.0=py310h02ab6af_1
  - charset-normalizer=3.4.4=py310haa95532_0
  - cryptography=46.0.3=py310habbc9f9_0
  - expat=2.7.3=h885b0b7_4
  - idna=3.11=py310haa95532_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.20=h83e8143_0
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - pycparser=2.23=py310haa95532_0
  - pygithub=2.8.1=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_1
  - python=3.10.19=h981015d_0
  - requests=2.32.5=py310haa95532_1
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - typing-extensions=4.15.0=py310haa95532_0
  - typing_extensions=4.15.0=py310haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py310haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_1
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - annotated-types==0.7.0
      - anyio==4.12.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - filelock==3.20.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - openai==2.14.0
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pynacl==1.6.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - safetensors==0.7.0
      - sniffio==1.3.1
      - sympy==1.14.0
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-inspection==0.4.2
      - tzdata==2025.3
prefix: D:\Anaconda\envs\codezip
